# Model setup
DAC.sample_rate: 44100
DAC.encoder_dim: 4
DAC.encoder_rates: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
DAC.latent_dim: 64
DAC.decoder_dim: 8192
DAC.decoder_rates: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
DAC.wavlm_decoder_rates: [2]
DAC.latent_noise_max: 0.1  # Maximum standard deviation for noise injection during training
DAC.causal: true
DAC.use_rmsnorm: true

# Quantization
DAC.n_codebooks: 9
DAC.codebook_size: 1024
DAC.codebook_dim: 8
DAC.quantizer_dropout: 1.0

# Discriminator
Discriminator.sample_rate: 44100
Discriminator.rates: []
Discriminator.periods: [2, 3, 5, 7, 11]
Discriminator.fft_sizes: [8192, 4096, 2048, 1024, 512]
Discriminator.bands:
  - [0.0, 0.1]
  - [0.1, 0.25]
  - [0.25, 0.5]
  - [0.5, 0.75]
  - [0.75, 1.0]

# Optimization
AdamW.betas: [0.8, 0.99]
AdamW.lr: 0.0001
ExponentialLR.gamma: 0.999996
Accelerator.gradient_accumulation_steps: 1

amp: false
val_batch_size: 100
device: cuda
num_iters: 250000
save_iters: [10000, 50000, 100000, 200000]
valid_freq: 1000
sample_freq: 10000
num_workers: 32
val_idx: [0, 1, 2, 3, 4, 5, 6, 7]
seed: 0
lambdas:
  mel/loss: 1.0
  stft/loss: 0.1
  waveform/loss: 10.0
  adv/feat_loss: 0.1
  adv/gen_loss: 0.1
  latents/loss: 0.1
  wavlm/cosine_loss: 1.0
  wavlm/mse_loss: 10.0

VolumeNorm.db: [const, -16]

# Transforms
build_transform.preprocess:
  - Identity
build_transform.augment_prob: 0.0
build_transform.augment:
  - Identity
build_transform.postprocess:
  - VolumeNorm
  - RescaleAudio
  - ShiftPhase

# Loss setup
MultiScaleSTFTLoss.window_lengths: [8192, 4096, 2048, 1024, 512]
MelSpectrogramLoss.n_mels: [5, 10, 20, 40, 80, 160, 320]
MelSpectrogramLoss.window_lengths: [32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]
MelSpectrogramLoss.mel_fmin: [0, 0, 0, 0, 0, 0, 0, 0]
MelSpectrogramLoss.mel_fmax: [null, null, null, null, null, null, null, null]
MelSpectrogramLoss.pow: 1.0
MelSpectrogramLoss.clamp_eps: 1.0e-5
MelSpectrogramLoss.mag_weight: 0.0
WavLMLoss.vad_frame_samples: 2048

# Data
batch_size: 256
train/AudioDataset.duration: 0.38
train/AudioDataset.n_examples: 10000000

val/AudioDataset.duration: 5.0
val/build_transform.augment_prob: 1.0
val/AudioDataset.n_examples: 250

test/AudioDataset.duration: 10.0
test/build_transform.augment_prob: 1.0
test/AudioDataset.n_examples: 1000

AudioLoader.shuffle: true
AudioDataset.without_replacement: true

train/build_dataset.folders:
  speech_fb:
    - /data/dac/daps/train
  speech_hq:
    - /data/dac/vctk
    - /data/dac/vocalset
    - /data/dac/read_speech
    - /data/dac/french_speech
  speech_uq:
    - /data/dac/emotional_speech/
    - /data/dac/common_voice/
    - /data/dac/german_speech/
    - /data/dac/russian_speech/
    - /data/dac/spanish_speech/
  music_hq:
    - /data/dac/musdb18hq/train
  music_uq:
    - /data/dac/mtg-jamendo
  general:
    - /data/dac/audioset/audios/unbalanced_train_segments/
    - /data/dac/audioset/audios/balanced_train_segments/

val/build_dataset.folders:
  speech_hq:
    - /data/dac/daps/val
  music_hq:
    - /data/dac/musdb18hq/test
  general:
    - /data/dac/audioset/audios/eval_segments/

test/build_dataset.folders:
  speech_hq:
    - /data/dac/daps/test
  music_hq:
    - /data/dac/musdb18hq/test
  general:
    - /data/dac/audioset/audios/eval_segments/

